#!/usr/bin/env bash

DIR=$(dirname "${BASH_SOURCE[0]}")
OPT="$(llvm-config --bindir)/opt"
exec ${OPT} -load-pass-plugin=${DIR}/../lib/libStackPasses.so \
    -aa-pipeline="default" \
    -passes="module(globalopt,deadargelim,strip-dead-prototypes,cgscc(inline-only,function-attrs,argpromotion,function(sccp,elim,adce,bugon,bugfree)))" \
    -disable-output \
	"$@" 2>&1

# TODO:
# timeout
# new-pm miss prune-eh
# parse flags with PassPlugin: -ignore-bugon-post -show-bugon-true
